-- CREATE TABLE products (
--     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     name text,
--     price numeric,
-- 	description text,
--     image text
-- );

-- CREATE TABLE categories (
--     id_category int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     name_category text
-- );

-- /*primero debo crear la columna en el campo que corresponde si*/
-- ALTER TABLE products 
-- ADD CONSTRAINT id_category FOREIGN KEY (id_category) REFERENCES categories (id_category);

CREATE DATABASE moto_store
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Chile.1252'
    LC_CTYPE = 'Spanish_Chile.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

CREATE TABLE public.products
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    price numeric,
    description text COLLATE pg_catalog."default",
    image text COLLATE pg_catalog."default",
    id_category integer,
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT id_category FOREIGN KEY (id_category)
        REFERENCES public.categories (id_category) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE public.categories
(
    id_category integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name_category text COLLATE pg_catalog."default",
    CONSTRAINT categories_pkey PRIMARY KEY (id_category)
)

TABLESPACE pg_default;

ALTER TABLE public.products
    OWNER to postgres;

